### ISSUE TITLE
wrong height after resize

### ISSUE THREAD

**Issue by fela** [shoes/shoes-deprecated#28] opened 2010-07-14 19:57 UTC
resizing a stack whose height that has been set to _100%_ changes its height, but the size doesn't change back when the stack is resized back

to _reproduce_ execute the following code: http://gist.github.com/475956 and
1. resize the window making it higher
2. then make it smaller again
the result: the stack keeps its biggest size; changing the height and than setting it again to _100%_ sets the correct height

**Comment by ashbb** [comment] 2010-07-15 14:21
IMHO, this behavior is reasonable.
Try to run this snippet:

```
Shoes.app width: 300, height: 300 do
  s = stack height: "100%" do
    w, h = para, para
    animate{w.text, h.text = s.width, s.height}
  end
end
```

Online demo is [here](http://www.rin-shun.com/shoes/shoes_issue_28.swf.html).

Because Shoes can show/use vertical scrollbar.

**Comment by steveklabnik** [comment] 2010-07-16 00:15
Closing due to not being a bug, exactly.

**Closed as completed** 2010-07-16 07:15 UTC

**Comment by fela** [comment] 2010-07-16 15:15
hm.. sorry, I'm don't understand how this is reasonable... I think that 99% of the time the user doesn't want that... nor is it what one would expect, that makes it a bug in my view.

I didn't mean to say that the result of `height` was wrong just that it would be much more reasonable if by default making the window smaller again would make the container smaller, if possible. Or more precisely, that after the screen is resized the sizes of the containers are recalculated using just their attributes set by the user: the user said the height should be is "100%", so after a resize that should be used to calculate the new height, _not_ the result of `height` (i.e. the height in pixels with the previous window size).

**Comment by ashbb** [comment] 2010-07-16 16:09
Oh,... okay. I understand what you're saying.　　　　
# Although I parsonally feel that this behavior is not so bad. :-P

But, Shoes can't tell the following difference so far:
- user resized the slot height by hand
- some elements touched the edge of the slot

So, Shoes makes scrollbar appear automatically in both cases...

**Comment by ashbb** [comment] 2010-07-17 01:27
Additional information.  
Width and height are not static constraints, just only initial parameters, I guess. ;-)

**Comment by fela** [comment] 2010-07-17 09:20
no because:
1. `@stack.style[:height]` returns `"100%"`
2. increasing the window height _does_ change the height of the stack, contrarily to what happens when you set the height to the available height in pixels (`@s = stack :height => height do ...`)

**Comment by ashbb** [comment] 2010-07-17 10:56
fela, you are totally right. :)  
But please run the following snippet and look at manual on `Position of a Slot`, [style()](http://shoes.heroku.com/manual/Position.html) section.

style[:height] is used to get the dimensions originally requested.

```
Shoes.app width: 300 do
  s = stack height: "100%" do
    background green
    h1, h2 = para, para
    button('set height pixel 200'){s.style height: 200}
    button('set height style "100%"'){s.style height: "100%"}
    animate{h1.text, h2.text = s.style[:height], s.height}
  end
end
```

Okay, I guess the problem is what "100%" means to.  
I think it means to `real height (max scrollable height)`.  
But you think `visible height (not max scrollable height)`.    

I'm not sure which is more reasonable, though...

**Comment by fela** [comment] 2010-07-17 11:26
hm... no, I'm okay with height meaning max scrollable height, and the code you are pasting does exactly what I expected, but the way I would have liked shoes to behave would not contradict your definition

I suppose you might eventually find a justification of the current behavior, but, IMHO, the one I'm suggesting is much more reasonable. I can't think of any use case where the user wants the current behavior, while anytime the user wants some stacks that span the full height of the window they usually don't want that resizing the window and then setting the size back adds unneeded scroll bars..

It's okay if you say changing it would require changes to big to be done before 3.0, but I can't see how the change would not be an improvement upon the current behavior

**Comment by fela** [comment] 2010-08-03 07:57
a workaround I found is to set `:height => -1`, you lose one pixel though

**Comment by ashbb** [comment] 2010-08-03 14:02
Ohhh, it works! I didn't notice at all. Awesome!
