### ISSUE TITLE
building from source on Ubuntu 10.10 fails because of missing libvlc_exception_t

### ISSUE THREAD

**Issue by abrz** [shoes/shoes-deprecated#76] opened 2010-11-21 20:49 UTC
Using 'rake VIDEO=0' per the building instructions on the wiki fails with the error
    In file included from ./shoes/app.h:40,
                 from shoes/effects.c:6:
    ./shoes/canvas.h:235: error: expected specifier-qualifier-list before ‘libvlc_exception_t’
    rake aborted!

The libvlc_exception_t type is not defined anywhere in /usr/include/vlc/*.h and all the related functions are missing as well (e.g., libvlc_exception_init). Here are the package details for libvlc-dev on my machine:

user@machine:/usr/include/vlc# dpkg -s libvlc-dev
Package: libvlc-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 352
Maintainer: Ubuntu Developers ubuntu-devel-discuss@lists.ubuntu.com
Architecture: amd64
Source: vlc
Version: 1.1.4-1ubuntu1
Replaces: libvlc0-dev
Depends: libvlc5 (= 1.1.4-1ubuntu1), libvlccore-dev, pkg-config
Description: development files for libvlc

**Comment by ccoupe** [comment] 2010-11-23 04:57
just use 'rake'. The current version of Shoes does not support Video and there is a rakefile bug with VIDEO=0.

**Comment by spiralofhope** [comment] 2010-11-23 11:11
I'm using Lubuntu 10.10 and Ruby 1.8.7 and I experience a similar issue.  I'm going to be updating to 1.9.2 and re-testing with just `rake`.

I'm just adding this comment so I can subscribe to updates on this issue.  Hopefully this second comment sticks.

**Comment by abrz** [comment] 2010-11-24 14:26
Even using 'rake' fails as there is a mismatch in the definition of rb_io_t included from rubyio.h. For me it was necessary to change line 345 of req/binject/ext/binject_c/binject.c, replacing fptr->fd with fptr->f to compile.

user@machine:~/src/gitrepos/shoes$ dpkg -S /usr/lib/ruby/1.8/x86_64-linux/rubyio.h  
ruby1.8-dev: /usr/lib/ruby/1.8/x86_64-linux/rubyio.h  
user@machine:~/src/gitrepos/shoes$ dpkg -s ruby1.8-dev  
Package: ruby1.8-dev  
Status: install ok installed  
Priority: optional  
Section: ruby  
Installed-Size: 2052  
Maintainer: Ubuntu Developers ubuntu-devel-discuss@lists.ubuntu.com  
Architecture: amd64  
Source: ruby1.8  
Version: 1.8.7.299-2

**Comment by ccoupe** [comment] 2010-11-24 22:10
Shoes as currently written, requires Ruby 1.9.1

Abrz, if you really want to go back to 1.8.7, there are other lines of code in binject.c and perhaps elsewhere that do not have #ifdef.  You'll have much debugging ahead.

**Comment by zzak** [comment] 2010-12-06 20:41
I know that, for whatever reason, the shoes in Ubuntu's repository (which is from 2008) requires the ruby1.8 package.

But hopefully that will be resolved soon, and we can get a more recent package in their repos!

**Comment by steveklabnik** [comment] 2011-01-04 21:12
Cecil has made a commit recently that makes 1.8.7 build. I'm going to update the instructions to leave off VIDEO, until that issue is resolved.

But since this effectively is a dupe of those other issues, I'm closing.

**Closed as completed by steveklabnik** 2011-01-04 21:12 UTC
