### ISSUE TITLE
Does not build on Snow Leopard

### ISSUE THREAD

**Issue by ghost** [shoes/shoes-deprecated#12] opened 2009-09-26 00:30 UTC

**Comment by ghost** [comment] 2009-09-26 00:33
Here's the thread I posted the build error in.

http://groups.google.com/group/shoooes/browse_thread/thread/af5a2686754315ee/19c8ccc0efb45fbe?#19c8ccc0efb45fbe

**Comment by melancholyfleur** [comment] 2010-01-31 23:25
My build error looked a little different:

http://pastebin.com/f3912d619

I got this after I followed the instructions here: 
http://wiki.github.com/shoes/shoes/buildingshoesonosx

and fixed my problem with building glib via this:
http://www.mail-archive.com/gtk-list@gnome.org/msg28747.html

so I'm not sure what the issue is. 64-bit, perhaps?

**Comment by DanielHeath** [comment] 2010-02-18 03:02
The basic issue is that the prebuilt deps are all i386 but GCC is expecting i686.
If I get all the deps built myself for i686, I'll package them and put them up for everyone else to use.

**Comment by atomicules** [comment] 2010-05-29 13:20
See mkelly's fork: http://github.com/mkelly/shoes and deps: http://github.com/mkelly/shoes/downloads

**Comment by tmcw** [comment] 2010-07-15 03:50
mkelly's fork is dead, are there any other options?

**Comment by atomicules** [comment] 2010-07-15 07:39
Yes, the main [shoes/shoes](http://github.com/shoes/shoes) now builds on Snow Leopard. See this [email thread](http://librelist.com/browser//shoes/2010/6/14/for-real-this-time-shoes-works-on-snow-leopard/), and the [wiki](http://wiki.github.com/shoes/shoes/building-shoes-64-bit-for-snow-leopard).

**Comment by steveklabnik** [comment] 2010-07-16 00:11
Yay for me! Closing.

**Closed as completed by steveklabnik** 2010-07-16 00:11 UTC
