### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by eandcproducts** [shoes/shoes-deprecated#197] opened 2012-04-03 16:24 UTC
I just downloaded shoes for linux, and it said:
  eval: 1: ./shoes: not found

Any ways to fix it?

**Comment by jrgifford** [comment] 2012-04-03 16:26
Duplicate of issue #157.  Thanks for sending this in, we're aware of it, and trying to figure out a usable fix.

**Closed as completed by jrgifford** 2012-04-03 16:26 UTC
