### ISSUE TITLE
Packaging fail

### ISSUE THREAD

**Issue by amedeo** [shoes/shoes-deprecated#15] opened 2010-01-09 19:34 UTC
Apparently there is a problem with the url http://hacketyhack.net  used in the code. That site is not available anymore.

**Comment by atomicules** [comment] 2010-01-28 23:42
This issue is a duplicate of issue 11. Please see that issue for a fix.

**Comment by steveklabnik** [comment] 2010-07-16 00:12
Closing due to duplicate.

**Closed as completed by steveklabnik** 2010-07-16 00:12 UTC
