### ISSUE TITLE
cursor shape doesn't change

### ISSUE THREAD

**Issue by ashbb** [shoes/shoes-deprecated#10] opened 2009-09-20 00:27 UTC
**cursor shape doesn't change.**

**Version**: Shoes-0.r1134 (Raisins) and 0.r1243 (Policeman)

**OS**: Window XP

**Error messages**: No error messages on the console

**ML Discussion**: [Isn't it strange this isn't documented anywhere? (cursor changing)](http://groups.google.co.jp/group/shoooes/browse_thread/thread/b369daef76c04f9e)

**To replicate**: run the following code

```
Shoes.app do
  flow do
    background pink
    para("point here")
    hover do
      self.cursor = :hand
    end
  end
  flow do
    para link('point there'){alert 'hi'}
  end
end
```

When mouse is hovering on the 'point there' link, cursor changes from 'arrow' to 'hand'. But on the 'point here', cursor doesn't change. This might be a bug on Windows only.

**Comment by atomicules** [comment] 2010-05-29 13:18
This somewhat works as intended on OSX PPC: Hovering on "point there" does nothing. Hovering on "point here" changes to hand, most of the time, sometimes it doesn't, but don't know why.

**Comment by ashbb** [comment] 2010-06-05 09:14
Fixed the bug. Commit is this: http://github.com/ashbb/shoes/commit/3687601b8a4fee189fe9aa27cb840c5467bb8b55

**Comment by steveklabnik** [comment] 2010-07-16 00:10
Closing

**Closed as completed by steveklabnik** 2010-07-16 00:10 UTC
