### ISSUE TITLE
ask_save_folder hangs (Linux only?)

### ISSUE THREAD

**Issue by ccoupe** [shoes/shoes-deprecated#94] opened 2011-03-20 03:46 UTC
example

Shoes.app do  
  @el = edit_line "#{Dir.pwd}"
  button "Pick Folder" do
    #@el.text = ask_open_folder #works
    @el.text = ask_save_folder  # hangs when dialog's save button is pushed
  end
end

**Comment by ashbb** [comment] 2011-03-20 04:32
Hi Cecil,

Umm,.. I ran your snippet on my Windows 7 and Ubuntu on VirtualBox.
It worked and got no error.

I'm using ruby 1.9.1p376 on Ubuntu on VirtualBox.

I'm not sure that is a reason, though...

But have to need to edit your code a little like this:

<pre>
edit_line text: "#{Dir.pwd}"
</pre>

This is one of difference from Red Shoes. :-P

ashbb

**Comment by ashbb** [comment] 2011-03-20 04:50
Oops, your question is about Red Shoes, sorry. xx-P

I confirmed with Red Shoes3 (0.r1514) for Windows and Red Shoes3 (0.r1520) for Linux on Ubuntu on VertualBox.

Both worked and got no error.

**Comment by steveklabnik** [comment] 2011-03-20 05:24
Both work fine for me on OSX.

Cecil, what linux are you using?

**Comment by ccoupe** [comment] 2011-03-20 06:04
Steve, the source code suggests that on OSX that ask_save_folder and ask_open_folder calls the same native code widget.  I'm using Ubuntu 10.10.

ashbb, shoes policeman (0.r1525) [x86_64-linux Ruby1.9.1]

All, --  it's a minor problem. It may even be a Ubuntu theme issue. Ick, if that is the case since I don't run the default theme. I'd rate this bug report priority something lower than minor. 

No big deal for my app  (see my blog http://werehosed.mvmanila.com/2011/03/19/check-your-isp/ for the link to the real app). Linux save_folder dialogs might well be thematic.

**Comment by steveklabnik** [comment] 2011-05-08 01:54
I just did this on ArchLinux, and it works.

I'm going to close this as 'wontfix,' @ccoupe, since you rate it so low. ;) We can always re-open if this starts happening to someone else.

**Closed as completed by steveklabnik** 2011-05-08 01:54 UTC
Labels: linux
