### ISSUE TITLE
Can't change button text

### ISSUE THREAD

**Issue by atomicules** [shoes/shoes-deprecated#19] opened 2010-02-05 12:31 UTC
See this Stackoverflow question: [How can I change the button text in Shoes?](http://stackoverflow.com/questions/1253176/how-can-i-change-the-button-text-in-shoes)

Changing a button's text via the style command does not change the actual text shown on the screen, even though if you inspect the style, the change is shown as having been made:

```
Shoes.app do
    @button = button "Click me" do
        @button.style(:text => "Again")
        para @button.style.inspect
    end
end
```

**Comment by ashbb** [comment] 2010-06-01 14:35
Yeah, Shoes can't change button text.  
But this is not a bug. Because Shoes doesn't support `text` and `text=` methods in the Button class so far.

```
Shoes.app do
  stack do
    para "button: #{Button.instance_methods.grep(/text/).join(' ')}"
    para "para: #{Para.instance_methods.grep(/text/).join(' ')}"
  end
end
```

Output is:

```
button: 
para: text text=
```

The `:text => "Again"` is just a hash entry, not a method.
Shoes allows you any hash entries as method arguments like this:

```
Shoes.app do
  bo = oval 100, 100, 100, fill: blue, say: 'I am blue.'
  ro = oval 300, 100, 100, fill: red, say: 'I am red.'
  [bo, ro].each{|o| o.click{alert o.style[:say]}}
end
```

**Comment by atomicules** [comment] 2010-06-01 14:39
Ok. This can go down as a feature for a release after Policeman. Unfortunately I don't have access to tag this as Mustard, etc.

**Comment by steveklabnik** [comment] 2010-07-16 00:13
Tagging as feature request.

**Comment by steveklabnik** [comment] 2011-01-04 20:29
I'm closing all feature request Issues, in favor of moving them to the wiki instead. This'll make it easier to lay them out into planning for future releases. Please [see here](https://github.com/shoes/shoes/wiki/Shoes-roadmap). Thanks!

**Closed as completed by steveklabnik** 2011-01-04 20:29 UTC
