### ISSUE TITLE
Rubygems version outdated : How to update it?

### ISSUE THREAD

**Issue by diogocsc** [shoes/shoes-deprecated#210] opened 2012-07-08 09:54 UTC
Hi, I'm trying to use httmultiparty with shoes, but i'm getting "multi_json requires RubyGems version >= 1.3.6 " . How can we update the rubygems version used by shoes? Thank you

**Comment by PragTob** [comment] 2012-07-08 11:30
Hi,

what version of Shoes are you using? The current develop should be rather up to date on the rubygems front. At least installing httmultiparty works on my machine. You'd have to compile it yourself though.

**Comment by diogocsc** [comment] 2012-07-08 12:52
Hi, I'm using the PoliceMan, and running under Windows 7 (if that might be relevant) . I have multiparty running fine on rails, and my local irb... What might i do to get this working?

**Comment by PragTob** [comment] 2012-07-08 12:58
I'm sorry but you will have to follow [this guide](https://github.com/shoes/shoes/wiki/Building-Shoes-on-Windows) in order to "build your own Shoes". The policeman release is outdated, we didn't manage to make a new release for various technical reasons and we're really sorry about that... I have no experience building Shoes under Windows but I think that the guide is rather complete, otherwise I think that @ashbb might be able to help.

**Comment by steveklabnik** [comment] 2012-07-08 13:38
Yes, you need to build your own Shoes. There's no way of updating RubyGems for an already-built Shoes.

I'm closing this since it's not a bug, but feel free to ask questions about actually building under windows here if the guide doesn't help you. :)

**Closed as completed by steveklabnik** 2012-07-08 13:38 UTC

**Comment by PragTob** [comment] 2012-07-08 14:08
The problem is that Shoes is ruby interpreter of it's own and therefore has its own ruby gems. If you don't want to compile Shoes on your own then you could try using [green shoes](http://ashbb.github.com/green_shoes/) which is a gem of its own, however it also involves some compilation.

**Comment by ashbb** [comment] 2012-07-08 15:51
Sorry for my late reply.
Try out the following snippet with [shoes-0.r1783.exe](http://www.rin-shun.com/shoes/shoes-0.r1783.exe). (Refer to [Red Shoes for Windows with Ruby 1.9.3p125](http://librelist.com/browser//shoes/2012/2/26/red-shoes-for-windows-with-ruby-1-9-3p125/#0bd1fdda4a71166a2634c5707a6b1aff))

``` ruby
Shoes.setup do
  gem 'multi_json'
end
Shoes.app do
  para require 'multi_json'
end
```

**Comment by diogocsc** [comment] 2012-07-08 18:59
Thank you all for your replies. I ended up using shoes-0.r1783.exe, which i just tested and works just fine, so many many thanks to ashbb. 
Guess we can expect a new Shoes version following Policeman for soon ;-). Cheers

**Comment by diogocsc** [comment] 2012-07-09 12:00
Hi ashbb, I managed to package a solution and run it locally, but when i try to pass the executable to someone who hasn't shoes installed, it seems that it's retrieving an old version and not the one i built the app with (r1783), since they get the same error i got earlier... Any ideas?

**Comment by ashbb** [comment] 2012-07-09 14:35
Ah, sorry. Because we don't prepare the environment for Shoes-0.r1783.
If you want to package your app with Shoes-0.r1783 (meaning: make the your_app.exe file included Shoes-0.r1783), you need to do the following steps by hand.
- I guess that you can find `latest_shoes.exe` under `HOME\.shoes\policeman\win32`.
- Rename Shoes-0.r1783.exe to latest_shoes.exe and replace the file you found on the first step.
- Then run Shoes and click `Package an App.` link and check `Windows` only and select `Yes, I want Shoes included.`.

**Comment by diogocsc** [comment] 2012-07-10 22:36
hmmm, this didn't work. I am having one other problem though, when i package my rb file more than once, it seems to be loading some kind of cache instead of my latest updated document....Any ideas on this one?

**Comment by ashbb** [comment] 2012-07-11 12:15
> hmmm, this didn't work.

Will you let me know about the detail?

> when i package my rb file more than once, it seems to be loading some kind of cache instead of my latest updated document

Oh, you found a bug!
I confirmed the problem on my Windows 7. But sorry, I have no solution for now...

So, please delete all cache files by hand and try to package again.
There are cache files under your TMP directory.

**Comment by diogocsc** [comment] 2012-07-11 12:54
Basically i copyed the new r1783.exe, and renamed it to latest_shoes.exe, and afterwards repackaged, following my interpretation of your instructions. When i passed it over to someone without shoes installed (well, in the meantime they probably had the previous version of shoes), it kept sending the same rubygems version message. 

To test this, i just uninstalled both version of shoes i had (1514 and 1783), and just tried and install from my shoes packaged with shoes file. 
With this i got two issues : One is that when i run, it keeps forever and ever looking for httmultiparty : http://screencast.com/t/rZceaobE

The other is that this shoes version that got installed as a different package screen, that only allows to package to .shy files (is this a known issue of this shoes version? - instead of an inline browse button with all the packaging options, i get a popup to imediatly choose the file and then this screen : http://screencast.com/t/KXsvwCQNA)

**Comment by ashbb** [comment] 2012-07-11 14:32
Umm,... strange. Watch [this](http://www.rin-shun.com/shoes/shoes-packaging-test.swf.html). On my Windows 7, looks fine, though...
