### ISSUE TITLE
Neither at_exit nor ObjectSpace.define_finalizer works in Shoes

### ISSUE THREAD

**Issue by guai** [shoes/shoes-deprecated#25] opened 2010-03-11 18:42 UTC
shoes raisins (0.r1134) [i386-mswin32]

**Comment by ashbb** [comment] 2010-05-02 11:58
Hi guai,

#1 at_exit

Yes. The at_exit method doesn't work in Shoes.
But, if you want to do something at closing your Shoes app, how about using `close` instead of `exit` ?

<pre><code>
Shoes.app do
  button 'exit' do
    Shoes.show_log
    info 'hi'
    close
  end
end
</code></pre>


#2 ObjectSpace.define_finalizer

Seems to work... Try the following snippet.
The message will appear on the window after a while (after GC execute).

<pre><code>
class Bar
  def Bar.callback
    proc{$msg = 'GC was executed.'}
  end
  def initialize
    ObjectSpace.define_finalizer(self, Bar.callback)
  end
end

Shoes.app do
  Bar.new
  msg = para
  every{msg.text = $msg}
end
</code></pre>


ps. I only confirmed the above two snippets on my Windows XP laptop with both Raisins (Shoes-0.r1134) and Policeman (Shoes-0.r1413)

ashbb

**Comment by atomicules** [comment] 2010-05-30 08:33
#1 Works on OSX PPC Shoes Raisins and Policeman (r1298)
#2 Works on OSX PPC Shoes Raisins, but not Policeman (message never appears) - don't know why (could be that build is a little bit behind with other changes?)

**Comment by steveklabnik** [comment] 2010-11-01 23:57
at_exit doesn't work either, but I'm not sure that it was intended to, is it, ash?

#2 works for me on Policeman.

**Comment by steveklabnik** [comment] 2010-11-02 13:02
Closing.

**Closed as completed by steveklabnik** 2010-11-02 13:02 UTC
