### ISSUE TITLE
Ubuntu Shoes install

### ISSUE THREAD

**Issue by remosewa** [shoes/shoes-deprecated#196] opened 2012-03-27 19:07 UTC
When I tried apt-get install shoes it worked but when I run a .shy file it says rubygems not found.

When I downloaded 3.1 from the website I got this:

root@vui-tools:~# ./shoes-3.1.0.run
Verifying archive integrity... All good.
Uncompressing Shoes...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
eval: 1: ./shoes: not found

**Comment by steveklabnik** [comment] 2012-03-27 19:13
`apt-get install shoes` will install a REALLY OLD shoes. We cannot fix this.

This seems to be a duplicate of #157, so I'm going to close this. Subscribe to that issue to get updates about it.

**Closed as completed by steveklabnik** 2012-03-27 19:13 UTC
Labels: linux, duplicate
